### ISSUE TITLE
Are there plans to support opentofu?

### ISSUE THREAD

**Issue by faraggi** [DontShaveTheYak/cf2tf#227]
Following the opentofu-hashicorp debacle, and as time goes by, there will eventually be differences between both codebases.

cf2tf will need to decide if it supports one or the either.

Or will there will be a need to fork this tool, too?    
`cf2ot`?

**Comment by shadycuz** [comment]
Hello @faraggi, 

Thanks for opening this issue. It was my understanding that from an HCL perspective (just the code) OpenTofu was commited to remaining compatible with regular Terraform. I haven't actually paid much attention to either Terraform or OpenTofu since the announcement/fork was created. So maybe they have walked back on that commitment. I think we are in a kinda wait and see mode. I agree that it is likely that they diverge given enough time. We will keep this open for now and when users report that they are unable to use the converted HCL with OpenTofu we will figure out what the path forward will look like.

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by shadycuz** [comment]
Now that I have used OpenTofu, there doesn't seem to be anything that needs doing. I will close this for now and if something changes we can open a new issue.
