### ISSUE TITLE
cf2tf  is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Arunk28** [DontShaveTheYak/cf2tf#260]
'cf2tf' is not recognized as an internal or external command,
operable program or batch file.

After installing  pip install cf2tf am trying to run the command not working 

even i went to that installation path and  trying to execute not working ! 

am not sure how to use ., seems there is no proper documentation is there

am using Windows

**Comment by shadycuz** [comment]
Hey @Arunk28 

I'm sorry you were not able to get the program to run. If the "pip install" command completes without errors, then you should be able to run the `cf2tf` command. 

Since you are unable to run the command, it appears the packages installed by pip are not on your PATH. This isn't an issue with cf2tf, it should affect any tool you install on your system via pip.

Since there are many ways you could have installed python, I can't really help you trouble shoot this issue any further. 

Do you have access to docker?
